package car_factory;

public enum Etapa {
    RECEPCION_Y_CLASIFICACION,
    CORTE_PIEZAS,
    ENSAMBLADO_CHASIS_CARROCERIA,
    PINTURA,
    ENSAMBLE_PARTES_MECANICAS,
    TERMINACION_EXTERIORES,
    ACABADOS_INTERIORES,
    VERIFICACION,
    ENTREGA;
}
